### ISSUE TITLE
Fisheye for planetarium

### ISSUE THREAD

**Issue by josterburg** [Cykyrios/Godot360#1]
For Fulldome-projection in planetarium I need the full fisheye-image. Is it possible to let me decide if I want the borders?
Otherwise pretty useful and finally enables me to use free software for Games in Fulldome :D

**Comment by Cykyrios** [comment]
If what you mean by borders is what the screenshot below shows, then there is currently no option to enable this effect. However, you can change the shader code [here](https://github.com/Cykyrios/Godot360/blob/08bba779124f9f285943b2fc4ac3fe9ff74fdc57/src/Camera360/Camera360.shader#L194), changing the 1.0 multiplier at the end of the line to a greater value will zoom out.

![fisheye](https://user-images.githubusercontent.com/53737317/95517832-0eb54c00-09c2-11eb-8732-5f5954ac976b.jpg)
